# -*- coding: utf-8 -*-
"""Aula-AoVivo_05-02-2024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Py7I4UYFlks0kZzHD9m0QvN3muEGbejh
"""

# array de objetos personalizados
nomes = ['Rafael', 'Artur', 'Karen', 'Júlia']
def achar_elemento(elem, arr):
  if elem in arr:
    print("Achamos o nome: " + elem)
  else:
    print("Não achamos o nome: " + elem)

nome_procurado = input("Por favor, insira um nome: ")

achar_elemento(nome_procurado, nomes)

#colocando repetição
nomes = ['Rafael', 'Artur', 'Karen', 'Júlia']

def achar_elemento(elem, arr):
  if elem in arr:
    print("Achamos o nome: " + elem)
  else:
    print("Não achamos o nome: " + elem)

while True:
  nome_procurado = input("Por favor, insira um nome (ou 's' para encerrar): ")
  if nome_procurado.lower() == 's':
    break
  achar_elemento(nome_procurado, nomes)

nomes = ['beltrano', 'ciclano', 'fulano']

def achar_elemento(elem, arr):
    if elem in arr:
        print("Achamos o nome: " + elem)
        return True
    else:
        print("Não achamos o nome: " + elem)
        return False

nome_procurado = input("Digite o nome de quem esta te devendo: ")

while not achar_elemento(nome_procurado, nomes):
    nome_procurado = input("Nome não encontrado. Por favor, digite outro nome: ")

resposta = input("Encontrou o nome, vai dar continuidade? (s/n): ")
if resposta.lower() == 's':
    print("Cobre o que ", nome_procurado, "está te devendo")
else:
    print("Certo, aqui está o nome: " + nome_procurado)

nomes = ["Rafael", "Artur", "Karen", "Julia"]

def achar_elemento(arr):
  achou = False
  frase = ""

  while (achou == False):
    print("Qual nome deseja procurar?")
    elem = input()

    for i in range (len(arr)):
      if arr[i] == elem:
        achou = True
        indice = i

    if(achou == False):
      frase = ("Não achamos o nome: " + elem)
      print(frase)
    else:
      frase = ("Encrontramos o nome " + elem + " no índice: " + str(indice))
      print(frase)



achar_elemento(nomes)

# array de objetos personalizados
nomes = ['Rafael', 'Artur', 'Karen', 'Júlia', 'Matheus']

def achar_elemento(arr):
    while True:
        elem = input("Digite o nome que deseja procurar na lista (ou 'sair' para encerrar): ")

        if elem.lower() == 'sair':
            break

        if elem in arr:
            print("Achamos o nome: " + elem)
        else:
            print("Não achamos o nome: " + elem)

# Chamada da função
achar_elemento(nomes)

# Sistema de Estoque
def manipular_estoque(arr):
  fechar = False

  while fechar == False:
    print("O que você deseja fazer? Digite um número: ")
    print("1. Ver Produtos em estoque")
    print("2. Alterar Produto")
    print("3. Fechar")
    print("---------------------------------------------")
    acao = input()

    if acao == "1":
      print("---------------------------------------------")
      print("Produtos em Estoque: ")
      for i in range(len(arr)):
        print(str(i) + "-" + arr[i])
    elif acao == "2":
      print("---------------------------------------------")
      print("Qual é o índice do Produto a ser alterado")
      indice = int(input())
      print("Qual é o novo Produto?")
      novo_produto = input()
      arr[indice] = novo_produto
      print("Produto " + novo_produto + " Adicionado com sucesso!")
      print("---------------------------------------------")
    elif acao == "3":
      print("---------------------------------------------")
      print("Fechando o Sistema!")
      fechar = True
    else
      print("---------------------------------------------")
      print("Por favor informe um código válido (1, 2 ou 3)")
      print("---------------------------------------------")
produtos = ["Pizza", "Hámburguer", "Porção", "Strogonof"]
manipular_estoque(produtos)