# -*- coding: utf-8 -*-
"""calcular_idade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BRJFqNrN9x93LqHBB5J5p5uPzdrXo9Za
"""

import datetime

def calcular_idade(ano_nascimento):
    ano_atual = datetime.datetime.now().year
    idade = ano_atual - ano_nascimento
    return idade

def main():
    while True:
        nome_completo = input("Digite seu nome completo: ")
        try:
            ano_nascimento = int(input("Digite seu ano de nascimento (entre 1922 e 2024): "))
            if ano_nascimento < 1922 or ano_nascimento > 2024:
                raise ValueError("Ano de nascimento fora do intervalo válido.")

            idade = calcular_idade(ano_nascimento)
            print(f"Olá, {nome_completo}! Você completou ou completará {idade} anos em 2024.")
            break

        except ValueError as e:
            print(f"Erro: {e}. Por favor, digite um ano de nascimento válido.")
            continue

if __name__ == "__main__":
    main()