# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i30Bawl6T_CHvp5OjVCMBAuTr1H9sfpE
"""

# Desafio: imprimindo em ordem decrescente
print("Desafio: imprimindo em ordem decrescente:")
for i in range(20, 0, -1): # percorre os números de 20 a 1, de trás para frente
  if i != 13: # se o número não for 13
    print(i) # imprime o número